swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /upload/Representative:
    # binds a127 app logic to a route
    x-swagger-router-controller: representative
    post:
      description: Uploads representative data, receives .xlsx file
      # used as the method name of the controller
      operationId: uploadRepresentativeFile
      parameters:
        - name: repData
          in: formData
          description: xlsx
          required: true
          type: file
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /seed/representative:
    x-swagger-router-controller: representative
    post:
      description: Processes representative file
      # used as the method name of the controller
      operationId: seedRepresentativeFile
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /representative:
    x-swagger-router-controller: representative
    get:
      description: Returns representative details
      operationId: getRepresentative
      parameters:
        - name: firstName
          in: query
          type: string
        - name: lastName
          in: query
          type: string
        - name: district
          in: query
          type: string
        - name: provinceParty
          in: query
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: inserts representative details
      operationId: insertRepresentative
      parameters:
        - name: repDetails
          in: body
          schema:
            type: object
            properties:
              id:
                type: integer
              firstName:
                type: string
              lastName:
                type: string
              provinceParty:
                type: string
              district:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      description: Updates representative details
      operationId: updateRepresentative
      parameters:
        - name: id
          in: query
          type: integer
        - name: updateDetails
          in: body
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              provinceParty:
                type: string
              district:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /asset:
    x-swagger-router-controller: asset
    get:
      description: Returns representative details
      operationId: getAsset
      parameters:
        - name: representativeId
          in: query
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: inserts representative details
      operationId: insertAsset
      parameters:
        - name: assetDetails
          in: body
          schema:
            type: object
            properties:
              totaAssets:
                type: number
              totalLiabilities:
                type: number
              representativeId:
                type: integer
              date:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    type: object
    # properties:
    #   timestamp: 
    #     type: object
    #     description: Date
    #     format: date-time
    #     example:  '2020-04-08T15:08:31.952Z'
    #   status:
    #     type: integer
    #     description: Status code
    #     example: 400
    #   message:
    #     type: string
    #     description: Error Message
    #     example:  Bad Request
  SuccessResponse:
    type: object
    # properties:
    #   timestamp: 
    #     type: object
    #     description: Date
    #     format: date-time
    #     example:  '2020-04-08T15:08:31.952Z'
    #   status:
    #     type: integer
    #     description: Status code
    #     example: 200
    #   message:
    #     type: string
    #     description: Success Message
    #     example:  Processing